# ./.devcontainer/docker-compose.yml
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - dev_node_modules:/workspace/node_modules
      - frontend_next_cache:/workspace/apps/web/.next
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env
    networks:
      - appnet

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - '5434:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      # Use $$ so expansion happens INSIDE the container shell
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pg_data: {}
  dev_node_modules: {}
  frontend_next_cache: {}
