services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - db
    environment:
      # You'll use this for Nest TypeORM config
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aimvp
    # VS Code will attach to this service

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aimvp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aimvp"]
      interval: 5s
      timeout: 3s
      retries: 20
